# GitHub Pages Configuration

# Enable GitHub Pages
url: "https://miisol.github.io"
baseurl: ""

# Site settings
title: "Miisol Ltd - AI Technology Solutions"
description: "Cutting-edge AI technology solutions, consulting services, and agent discovery platforms for modern businesses."
author: "Miisol Ltd"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .vscode/
  - node_modules/
  - package*.json

# Include files
include:
  - _redirects

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
logo: /assets/images/logo.svg

# Social media
twitter:
  username: miisol_ltd
  card: summary_large_image

# Google Analytics (add your tracking ID)
# google_analytics: UA-XXXXXXXX-X

# Custom domain (uncomment and update if using custom domain)
# url: "https://miisol.com"
# enforce_ssl: miisol.com
